# Generated by Django 4.2 on 2023-06-13 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(max_length=255)),
                ('caracteristicas', models.CharField(max_length=1000)),
                ('nutrientes', models.CharField(max_length=255)),
                ('procsiembra', models.CharField(max_length=1000)),
                ('cuidados', models.CharField(max_length=1000)),
                ('requerimientos', models.CharField(max_length=1000)),
                ('cosecha', models.CharField(max_length=1000)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HuertoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('huerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huertourbano.huerto')),
            ],
        ),
        migrations.CreateModel(
            name='HuertoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='huerto_images/')),
                ('huerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huertourbano.huerto')),
            ],
        ),
    ]
