# Generated by Django 4.2 on 2023-06-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huertourbano', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huertoimage',
            name='huerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='huertourbano.huerto'),
        ),
        migrations.AlterField(
            model_name='huertovideo',
            name='huerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='huertourbano.huerto'),
        ),
    ]
