# Generated by Django 4.2 on 2023-07-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huertourbano', '0002_alter_huertoimage_huerto_alter_huertovideo_huerto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
